models:
- description: Word embeddings from glove-twitter-25 model
  file: glove-twitter-25.json
  name: glove-twitter-25
- description: Word embeddings from glove-wiki-gigaword-100 model
  file: glove-wiki-gigaword-100.json
  name: glove-wiki-gigaword-100
- description: Word embeddings from word2vec-google-news-300 model
  file: word2vec-google-news-300.json
  name: word2vec-google-news-300
